security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: in_memory
            form_login: 
                login_path: login
                check_path: login

    providers:
        in_memory:
            memory: ~

