[build.environment]
  PHP_VERSION = "8.2"

[build]
  publish = "public"
  command = "composer install && php bin/console cache:clear --env=prod && php bin/console assets:install public"

  [[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200